from tkinter import *
root=Tk()
root.title("LOGIN PLS or else..")
root.geometry("700x700")
root.config(background="light pink")
l1=Label(root,text="UsErNaMe..",bg="white",fg="black")
l1.place(x=50,y=100)
l2=Label(root,text="PaSsWoRd..",bg="white",fg="black")
l2.place(x=50,y=150)
entry1=Entry(root,width=30)
entry1.place(x=150, y=100)
entry2=Entry(root,width=30)
entry2.place(x=150, y=150)
root.mainloop()